### ISSUE TITLE
Linux server crashes when changing maps

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#182] opened 2016-10-31 12:32 UTC
Need to investigate this ASAP.

**Comment by ensiform** [comment] 2016-10-31 19:40
I couldn't reproduce any issues on Debug build currently.

Maybe someone or I can at another time check with RelWithDebInfo build.

**Comment by AlexCSilva** [comment] 2016-10-31 22:29
I didn't think to start  an issue like this. Also I think for windows build, I'm not sure if it is map_restart. However, when a round ends and you ready up it seems to crash instead of restarting the map. (Have map cycle turned off for the moment on my server).

**Comment by eezstreet** [comment] 2016-11-01 07:37
No sign that the Windows issue is related to the Linux one as of yet.

**Comment by ensiform** [comment] 2016-11-01 19:11
@eezstreet what makes you say that?

**Comment by eezstreet** [comment] 2016-11-01 20:59
Windows Dedicated server crash happens when you close out with the X button and only that - `map_restart` and `quit` don't trigger the crash. The Windows dedicated server crash is because the game module gets `G_ShutdownGame` called and an extra frame is getting through. I'm not sure why yet.

**Comment by ensiform** [comment] 2016-11-02 00:00
The x button calls "quit" which calls killserver soo....

**Comment by eezstreet** [comment] 2016-11-02 06:40
@AlexCSilva @ooxavenue give it a whirl and see if it causes issues

**Comment by AlexCSilva** [comment] 2016-11-02 12:18
Changing maps still crashes though i might not have latest assets, just builded server and jampgame

**Comment by ensiform** [comment] 2016-11-02 15:17
No it doesn't. Its th exact same crash.  Update your builds properly.

**Comment by AlexCSilva** [comment] 2016-11-03 06:26
Okay it works now, from making a 64bit build on the same vps that runs server. Can probably close this issue for now.

**Closed** 2016-11-03 07:40 UTC
Labels: bug, potentially-fixed, priority:high

**Comment by AlexCSilva** [comment] 2016-11-05 23:09
It seems to crash again but only when changing to a different map. Doing map_restart or simply changing to same map by /map or /devmap doesn't crash though. From doing some more testing, it appears it doesn't crash at all when changing maps if no one is connected.

**Comment by ensiform** [comment] 2016-11-06 02:14
Pretty sure its a different issue entirely.  Or maybe yours was also a combination of more than 1 all along.

**Comment by AlexCSilva** [comment] 2016-11-06 02:47
Yeah maybe
