### ISSUE TITLE
Cheats Enabled by Default

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#156] opened 2016-02-09 02:15 UTC
God mode and noclip are allowed without devmap and/or admin login access.  All players can make themselves game-breakingly invincible by default.

Is this intentional?  If not, let's get this reverted back to normal.  If players want to cheat they need to either login as an admin or use devmap.

**Comment by eezstreet** [comment] 2016-04-21 22:15
Debug and set a breakpoint on CheatsOk in g_cmds.cpp.

**Comment by AlexCSilva** [comment] 2016-08-08 07:29
Is this fixed?

**Comment by DarthFutuza** [comment] 2016-08-08 08:28
Haven't looked at it yet, don't think anyone fixed it.

**Comment by eezstreet** [comment] 2016-10-26 10:11
Not a bug, as it turns out. Cheats are enabled for the host of games.

**Comment by DarthFutuza** [comment] 2016-10-26 10:19
I'm not sure we should close the issue since even though it's a feature it's a bad feature, why allow the host to cheat by default? also weirdly enough it doesn't allow commands like npc spawn stormtrooper, only god and noclip, so cheats are still technically disabled, it's only those two commands that work afaik.  Will try to look at it properly tomorrow so we can get this closed soon.

**Comment by Silverfang22** [comment] 2016-10-28 07:34
God and Noclip appear to not be tied to cheats at all.

**Comment by DarthFutuza** [comment] 2016-10-28 18:42
I'm putting the bug label back on, since it's not related to cheats being "enabled" or not, God mode and noclip just magically work regardless of whether cheats are enabled or not.  Unfortunately I haven't had a chance to look at it yet, and only have about 2 hours of time to work on JKG today, so I probably won't get to this.

**Comment by eezstreet** [comment] 2016-10-30 03:04
Seems to be fixed via b9c792ddd1cc4731d3b0fc858a39825577d4a7d0 - need further testing to verify

**Closed** 2016-10-30 08:30 UTC
Labels: bug, potentially-fixed, priority:medium
